language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
    - dist

install:
  - npm install

script:
  - npm run chk:data
  - npm run prettier
  - npm run build

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
